<?php


function hide_reviewer_in_fields(&$hidee) {
	hide($hidee['field_project_review_r1_in']);
	hide($hidee['field_project_review_r2_in']);
	hide($hidee['field_project_review_r3_in']);
}

function bfi_form_tweaks_form_alter(&$form, &$form_state, $form_id) {

  dpm($form);

  switch ($form_id) {
  	case 'project_node_form':
		$count_reviewer = count($form['field_project_reviewers']['und']) - 13;
  		for ($i = 0; $i < $count_reviewer; $i++) {
	  		hide_reviewer_in_fields($form['field_project_reviewers']['und'][$i]['relation_options']);
  		}
  		break;
  	case 'relation_ui_edit_form':
  		hide_reviewer_in_fields($form);
  		break;
  }

}
