<?php

/*
function hide_reviewer_in_fields(&$hidee) {		// For hiding review_in fields
	hide($hidee['field_project_review_r1_in']);
	hide($hidee['field_project_review_r2_in']);
	hide($hidee['field_project_review_r3_in']);
}

/*
 * Implementing hook_form_alter
 
function bfi_form_tweaks_form_alter(&$form, &$form_state, $form_id) {

//  dpm($form);

  switch ($form_id) {
  	case 'project_node_form':
		$count_reviewer = count($form['field_project_reviewers']['und']) - 13;
  		for ($i = 0; $i < $count_reviewer; $i++) {
	  		hide_reviewer_in_fields($form['field_project_reviewers']['und'][$i]['relation_options']);
  		}
  		break;
  	case 'relation_ui_edit_form':
  		hide_reviewer_in_fields($form);
  		break;
  }

}
*/

$mod_name = 'bfi_form_tweaks';
$path = drupal_get_path('module', $mod_name).'/css/'.$mod_name.'.css';
// Currently set to inline, which is less than idea, as the css file reference wouldn't work for some reason. Debug this when have time.
$inline = '
form table div.field-name-field-project-review-r1-in,
form table div.field-name-field-project-review-r2-in,
form table div.field-name-field-project-review-r3-in {
  display: none !important;
}

body.fubik div.form-item div.description {
  bottom: 110%;
}';
drupal_add_css($inline, array('type'=>'inline', 'group' => CSS_DEFAULT, 'every_page' => TRUE));
