<?php

/**
 * Implements hook_entity_info().
 */
function nodereview_entity_info() {
  $return = array(
    'nodereview' => array(
      'label' => t('nodereview'),
      'entity class' => 'NodeReview',
      'controller class' => 'NodeReviewController',
      'base table' => 'nodereview',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'nrid',
        'bundle' => 'type',
      ),
      'bundle keys' => array(
        'bundle' => 'type',
      ),
      'bundles' => array(),
      'load hook' => 'nodereview_load',
      'view modes' => array(
        'full' => array(
          'label' => t('Default'),
          'custom settings' => FALSE,
        ),
      ),
      'label callback' => 'entity_class_label',
      'uri callback' => 'entity_class_uri',
      'module' => 'nodereview',
      'access callback' => 'nodereview_access',
    ),
  );
  $return['nodereview_type'] = array(
    'label' => t('Node Review Type'),
    'entity class' => 'NodeReviewType',
    'controller class' => 'NodeReviewTypeController',
    'base table' => 'nodereview_type',
    'fieldable' => FALSE,
    'bundle of' => 'nodereview',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'module' => 'nodereview',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/structure/nodereview-types',
      'file' => 'nodereview.admin.inc',
      'controller class' => 'NodeReviewTypeUIController',
    ),
    'access callback' => 'nodereview_type_access',
  );

  return $return;
}

/**
 * Implements hook_entity_info_alter().
 */
function nodereview_entity_info_alter(&$entity_info) {
  foreach (nodereview_types() as $type => $info) {
    $entity_info['nodereview']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/nodereview-types/manage/%nodereview_type',
        'real path' => 'admin/structure/nodereview-types/manage/' . $type,
        'bundle argument' => 4,
      ),
    );
  }
}

/**
 * Implements hook_menu().
 */
function nodereview_menu() {
  $items = array();

  $items['nodereview/add'] = array(
    'title' => 'Add Node Review',
    'page callback' => 'nodereview_admin_add_page',
    'access arguments' => array('administer nodereview entities'),
    'file' => 'nodereview.admin.inc',
    'type' => MENU_LOCAL_ACTION,
    'tab_parent' => 'nodereview',
    'tab_root' => 'nodereview',
  );

  $nodereview_uri = 'nodereview/%nodereview';
  $nodereview_uri_argument_position = 1;

  $items[$nodereview_uri] = array(
    'title callback' => 'entity_label',
    'title arguments' => array('nodereview', $nodereview_uri_argument_position),
    'page callback' => 'nodereview_view',
    'page arguments' => array($nodereview_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'nodereview', $nodereview_uri_argument_position),
    'file' => 'nodereview.pages.inc',
  );

  $items[$nodereview_uri . '/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items[$nodereview_uri . '/delete'] = array(
    'title' => 'Delete Node Review',
    'title callback' => 'nodereview_label',
    'title arguments' => array($nodereview_uri_argument_position),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nodereview_delete_form', $nodereview_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'nodereview', $nodereview_uri_argument_position),
    'file' => 'nodereview.admin.inc',
  );

  $items[$nodereview_uri . '/edit'] = array(
    'title' => 'Edit Node Review',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nodereview_form', $nodereview_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'nodereview', $nodereview_uri_argument_position),
    'file' => 'nodereview.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  foreach (nodereview_types() as $type => $info) {
    $items['nodereview/add/' . $type] = array(
      'title' => 'Add Node Review',
      'page callback' => 'nodereview_add',
      'page arguments' => array(2),
      'access callback' => 'entity_access',
      'access arguments' => array('create', 'nodereview', $type),
      'file' => 'nodereview.admin.inc',
    );
  }

  $items['admin/structure/nodereview-types/%nodereview_type/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nodereview_type_form_delete_confirm', 4),
    'access arguments' => array('administer nodereview types'),
    'weight' => 1,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'nodereview.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function nodereview_permission() {
  $permissions = array(
    'administer nodereview types' => array(
      'title' => t('Administer nodereview types'),
      'description' => t('Allows users to configure nodereview types and their fields.'),
      'restrict access' => TRUE,
    ),
    'create nodereview entities' => array(
      'title' => t('Create nodereviews'),
      'description' => t('Allows users to create nodereviews.'),
      'restrict access' => TRUE,
    ),
    'view nodereview entities' => array(
      'title' => t('View nodereviews'),
      'description' => t('Allows users to view nodereviews.'),
      'restrict access' => TRUE,
    ),
    'edit any nodereview entities' => array(
      'title' => t('Edit any nodereviews'),
      'description' => t('Allows users to edit any nodereviews.'),
      'restrict access' => TRUE,
    ),
    'edit own nodereview entities' => array(
      'title' => t('Edit own nodereviews'),
      'description' => t('Allows users to edit own nodereviews.'),
      'restrict access' => TRUE,
    ),
  );

  return $permissions;
}


/**
 * Implements hook_entity_property_info_alter().
 */
function nodereview_entity_property_info_alter(&$info) {
  $properties = &$info['nodereview']['properties'];
  $properties['created'] = array(
    'label' => t("Date created"),
    'type' => 'date',
    'description' => t("The date the node was posted."),
    'setter callback' => 'entity_property_verbatim_set',
    'setter permission' => 'administer nodes',
    'schema field' => 'created',
  );
  $properties['changed'] = array(
    'label' => t("Date changed"),
    'type' => 'date',
    'schema field' => 'changed',
    'description' => t("The date the node was most recently updated."),
  );
  $properties['uid'] = array(
    'label' => t("Author"),
    'type' => 'user',
    'description' => t("The author of the nodereview."),
    'setter callback' => 'entity_property_verbatim_set',
    'setter permission' => 'administer nodereview entities',
    'required' => TRUE,
    'schema field' => 'uid',
  );
}

/**
 * Access callback for nodereview.
 */
function nodereview_access($op, $nodereview, $account = NULL, $entity_type = NULL) {
  global $user;

  if (!isset($account)) {
    $account = $user;
  }
  switch ($op) {
    case 'create':
      return user_access('administer nodereview entities', $account)
          || user_access('create nodereview entities', $account);
    case 'view':
      return user_access('administer nodereview entities', $account)
          || user_access('view nodereview entities', $account);
    case 'edit':
      return user_access('administer nodereview entities')
          || user_access('edit any nodereview entities')
          || (user_access('edit own nodereview entities') && ($nodereview->uid == $account->uid));
  }
}

/**
 * Load a nodereview.
 */
function nodereview_load($nrid, $reset = FALSE) {
  $nodereviews = nodereview_load_multiple(array($nrid), array(), $reset);
  return reset($nodereviews);
}

/**
 * Load multiple nodereviews based on certain conditions.
 */
function nodereview_load_multiple($nrids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('nodereview', $nrids, $conditions, $reset);
}

/**
 * Save nodereview.
 */
function nodereview_save($nodereview) {
  entity_save('nodereview', $nodereview);
}

/**
 * Delete single nodereview.
 */
function nodereview_delete($nodereview) {
  entity_delete('nodereview', entity_id('nodereview' ,$nodereview));
}

/**
 * Delete multiple nodereviews.
 */
function nodereview_delete_multiple($nodereview_ids) {
  entity_delete_multiple('nodereview', $nodereview_ids);
}

/**
 * Access callback for nodereview Type.
 */
function nodereview_type_access($op, $entity = NULL) {
  return user_access('administer nodereview types');
}

/**
 * Load nodereview Type.
 */
function nodereview_type_load($nodereview_type) {
  return nodereview_types($nodereview_type);
}

/**
 * List of nodereview Types.
 */
function nodereview_types($type_name = NULL) {
  $types = entity_load_multiple_by_name('nodereview_type', isset($type_name) ? array($type_name) : FALSE);
  return isset($type_name) ? reset($types) : $types;
}

/**
 * Save nodereview type entity.
 */
function nodereview_type_save($nodereview_type) {
  entity_save('nodereview_type', $nodereview_type);
}

/**
 * Delete single case type.
 */
function nodereview_type_delete($nodereview_type) {
  entity_delete('nodereview_type', entity_id('nodereview_type' ,$nodereview_type));
}

/**
 * Delete multiple case types.
 */
function nodereview_type_delete_multiple($nodereview_type_ids) {
  entity_delete_multiple('nodereview_type', $nodereview_type_ids);
}

/**
  * Implements hook_views_api().
  */
function nodereview_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'nodereview'),
  );
}

