<?php

/**
 * For Rules code, check bfi_project_review.rules.inc
 */

/**
 * Implements hook_form_alter
 */
function bfi_project_review_form_alter(&$form, &$form_state, $form_id) {

	switch ($form_id) {
	  case 'bfc_project_review_entityform_edit_form':
			$node = menu_get_object();
			$node_wrapper = entity_metadata_wrapper('node', $node);
/*			$form_wrapper = entity_metadata_wrapper('form', $form);
			switch ($node_wrapper->field_project_round->value()) {
				case 1:
					$form_wrapper->entity->title->set('Round 1');
					$form_wrapper->save();
					break;
			}
*/	  	break;
  }

}
